  - name: Monit | Check if is installed
    command: dpkg-query -W monit
    when: ansible_os_family == "Debian"
    register: monit_check_deb
    failed_when: monit_check_deb.rc > 1
    changed_when: monit_check_deb.rc == 1
    tags:
      - monit

  - name: Monit | package dependencies
    apt: pkg="{{item}}" state="present"
    become: yes
    with_items:
      - libssl-dev
      - libc6
    tags:
      - monit

  - name: Monit | Download
    get_url: url="http://us.archive.ubuntu.com/ubuntu/pool/universe/m/monit/monit_{{monit_version}}_amd64.deb" dest="/tmp/monit_{{monit_version}}_amd64.deb"
#                 https://mmonit.com/monit/dist/binary/5.19.0/monit-5.19.0-linux-x64.tar.gz
#                 http://us.archive.ubuntu.com/ubuntu/pool/universe/m/monit/monit_5.19.0-1_amd64.deb
    when: monit_check_deb.rc == 1
    tags:
      - monit

  - name: Monit | Install
    apt: deb="/tmp/monit_{{monit_version}}_amd64.deb"
    when: monit_check_deb.rc == 1
    become: yes
    tags:
      - monit

  - name: Monit | Configure preset confs
    template: src={{role_dir}}/templates/presets/{{item}}.conf.j2 dest=/etc/monit/conf.d/{{item}}.conf
    with_items: "{{monit_presets}}"
    become: yes
    tags:
      - monit
      - update

  - name: Monit | Restart
    service: name=monit state=restarted
    become: yes
    when: docker_test is not defined
    tags:
      - monit
      - update
