---
- hosts: www

  vars:
    - root_dir: ..


  pre_tasks:
    - debug: msg="Pre tasks section"

  roles:
     - {
         role: "sa-nginx"
       }
     - {
         role: "sa-monit"
       }


  tasks:
    - debug: msg="Tasks section"
